name: Workflow docker compose

on: 
  push:
    branches:
      - master

jobs:
  deploy-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurando y conectando al servidor de digital ocean...
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts
      
      - name: Conectando y desplegando el compose...
        run: |
          ssh -i  ~/.ssh/id_rsa root@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
            cd /root/codigo/docker-scale-python
            git pull origin master
            docker compose down
            docker compose up -d --build
          EOF

